version: "3"
services:
  server:
    command: jekyll serve
    image: jekyll/jekyll:latest
    volumes:
      - $PWD:/srv/jekyll
      - $PWD/vendor/bundle:/usr/local/bundle
    ports:
      -   127.0.0.1:4000:4000 # website.rack12923
